//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAPResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LAPResources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening Acrobat Reader. Make sure you have Acrobat Reader installed correctly and try again..
        /// </summary>
        public static string Error_Message_No_AcroRD32 {
            get {
                return ResourceManager.GetString("Error_Message_No_AcroRD32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Left Object].
        /// </summary>
        public static string LPSpy_AddObjectsWindow_LeftObject {
            get {
                return ResourceManager.GetString("LPSpy_AddObjectsWindow_LeftObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Right Object].
        /// </summary>
        public static string LPSpy_AddObjectsWindow_RightObject {
            get {
                return ResourceManager.GetString("LPSpy_AddObjectsWindow_RightObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to insert checked object(s) into repository.
        /// </summary>
        public static string LPSPY_BreadCrumbWindow_AddObjectToRepository {
            get {
                return ResourceManager.GetString("LPSPY_BreadCrumbWindow_AddObjectToRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string LPSPY_Confirm {
            get {
                return ResourceManager.GetString("LPSPY_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element is no longer available, please reselect the element.
        /// </summary>
        public static string LPSpy_ElementNotAvailableException {
            get {
                return ResourceManager.GetString("LPSpy_ElementNotAvailableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File changed outside the Manager, do you want to reload?.
        /// </summary>
        public static string LPSpy_ModelFileHandler_ReloadChangedFile {
            get {
                return ResourceManager.GetString("LPSpy_ModelFileHandler_ReloadChangedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find {0}.
        /// </summary>
        public static string LPSpy_SpyMainWindow_CannotfindFormat {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_CannotfindFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find this object.
        /// </summary>
        public static string LPSpy_SpyMainWindow_CannotFindObjectMsg {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_CannotFindObjectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please capture the snapshot of the control before editing virtual controls.
        /// </summary>
        public static string LPSpy_SpyMainWindow_CaptureSnapshotFirst {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_CaptureSnapshotFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; cannot be opened and will be removed from the Recent list(s).
        /// </summary>
        public static string LPSpy_SpyMainWindow_FileRemovedFromRecentList {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_FileRemovedFromRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0}.
        /// </summary>
        public static string LPSpy_SpyMainWindow_FoundFormat {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_FoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying....
        /// </summary>
        public static string LPSpy_SpyMainWindow_Identifying {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_Identifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying {0}.
        /// </summary>
        public static string LPSpy_SpyMainWindow_IdentifyingFormat {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_IdentifyingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format, please check log files for more details.
        /// </summary>
        public static string LPSpy_SpyMainWindow_InvalidFileFormat {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name : {0} is not unique..
        /// </summary>
        public static string LPSpy_SpyMainWindow_ObjNameNotUniqueMsg {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_ObjNameNotUniqueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object name is same as other, it will be update:{0}.
        /// </summary>
        public static string LPSpy_SpyMainWindow_ObjNameSameMsg {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_ObjNameSameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a node..
        /// </summary>
        public static string LPSpy_SpyMainWindow_PleaseSelectNode {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_PleaseSelectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object you selected in your application is not of the same control type as the object selected in the tree control. To update the selected object, the object control types must match..
        /// </summary>
        public static string LPSpy_SpyMainWindow_RefreshobjNotMatchWarningMsg {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_RefreshobjNotMatchWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a node to refresh.
        /// </summary>
        public static string LPSpy_SpyMainWindow_RefreshobjWarningMsg {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_RefreshobjWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LPSpy_SpyMainWindow_RefreshobjWarningTitle {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_RefreshobjWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to restart application to take effect, restart now?.
        /// </summary>
        public static string LPSpy_SpyMainWindow_RetartToTakeEffect {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_RetartToTakeEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save it?.
        /// </summary>
        public static string LPSpy_SpyMainWindow_SaveWarningMsg {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_SaveWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an object from right to edit.
        /// </summary>
        public static string LPSpy_SpyMainWindow_SelectobjMsg {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_SelectobjMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a node to highlight..
        /// </summary>
        public static string LPSpy_SpyMainWindow_SelNodeWarningMsg {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_SelNodeWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be added.
        /// </summary>
        public static string LPSpy_SpyMainWindow_ToBeAdded {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_ToBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Model Manager.
        /// </summary>
        public static string LPSpy_SpyMainWindow_WindowTitle {
            get {
                return ResourceManager.GetString("LPSpy_SpyMainWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string LPSpy_ToMethodViewer_GroupNameMethods {
            get {
                return ResourceManager.GetString("LPSpy_ToMethodViewer_GroupNameMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string LPSpy_ToMethodViewer_GroupNameProperties {
            get {
                return ResourceManager.GetString("LPSpy_ToMethodViewer_GroupNameProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
